name: automl
version: '3'

services:
  dev:
    build:
      target: dev
      context: .
      args:
        USERNAME: ${USERNAME}
        UID: ${UID}
        GID: ${GID}
        PYTORCH_VERSION: ${PYTORCH_VERSION}
        CUDA_VERSION: ${CUDA_VERSION}
        CUDNN_VERSION: ${CUDNN_VERSION}
        CONTAINER_CODE_PATH: ${CONTAINER_CODE_PATH}
        CONTAINER_TORCH_CACHE_PATH: ${CONTAINER_TORCH_CACHE_PATH}
        CONTAINER_VSCODE_PATH: ${CONTAINER_VSCODE_PATH}

    volumes:
      - torch_cache:${CONTAINER_TORCH_CACHE_PATH}
      - vscode:${CONTAINER_VSCODE_PATH}
      - ${HOST_CODE_PATH}/automl:${CONTAINER_CODE_PATH}/automl
      - ${HOST_MODELS_PATH}:${CONTAINER_MODELS_PATH}:ro

    shm_size: ${SHM_SIZE} 

    environment:
      TERM: 'screen-256color'

    tty: true
    init: true

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

  dev_naslib:
    build:
      target: dev_nas
      context: .
      args:
        USERNAME: ${USERNAME}
        UID: ${UID}
        GID: ${GID}
        PYTORCH_VERSION: ${PYTORCH_VERSION}
        CUDA_VERSION: ${CUDA_VERSION}
        CUDNN_VERSION: ${CUDNN_VERSION}
        CONTAINER_CODE_PATH: ${CONTAINER_CODE_PATH}
        CONTAINER_TORCH_CACHE_PATH: ${CONTAINER_TORCH_CACHE_PATH}
        CONTAINER_VSCODE_PATH: ${CONTAINER_VSCODE_PATH}

    volumes:
      - torch_cache:${CONTAINER_TORCH_CACHE_PATH}
      - vscode:${CONTAINER_VSCODE_PATH}
      - ${HOST_CODE_PATH}/automl:${CONTAINER_CODE_PATH}/automl
      - ${HOST_MODELS_PATH}:${CONTAINER_MODELS_PATH}:ro

    shm_size: ${SHM_SIZE} 

    environment:
      TERM: 'screen-256color'

    tty: true
    init: true

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
volumes:
  vscode:
    external: true
  torch_cache: 
    external: true

