name: mmdet
# Defined to easily add to a service for debugging
x-executable: &executable
  tty: true
  init: true

x-torch-args: &torch-args
  PYTORCH_VERSION: ${PYTORCH_VERSION}
  CUDA_VERSION: ${CUDA_VERSION}
  CUDNN_VERSION: ${CUDNN_VERSION}

x-mmlab-args: &mmlab-args
  MMENGINE_VERSION: ${MMENGINE_VERSION}
  MMCV_VERSION: ${MMCV_VERSION}
  MIM_VERSION: ${MIM_VERSION}

x-build-args: &build-args
  <<: 
    - *mmlab-args
    - *torch-args

# Defined here to have shorter service definition
x-dev-args: &dev-args
  USERNAME: ${USERNAME}
  UID: ${UID}
  GID: ${GID}
  CONTAINER_HOME_PATH: ${CONTAINER_HOME_PATH}
  CONTAINER_CODE_PATH: ${CONTAINER_CODE_PATH}
  CONTAINER_TORCH_CACHE_PATH: ${CONTAINER_TORCH_CACHE_PATH}
  CONTAINER_VSCODE_PATH: ${CONTAINER_VSCODE_PATH}

# Defined here to have shorter service definition
x-dev-volumes: &dev-volumes
  - /etc/localtime:/etc/localtime:ro
  - ./entrypoint.sh:/entrypoint.sh
  - torch_cache:${CONTAINER_TORCH_CACHE_PATH}
  - vscode:${CONTAINER_VSCODE_PATH}
  - ${HOST_CODE_PATH}/mmdet:${CONTAINER_CODE_PATH}/mmdet
  - ${HOST_CODE_PATH}/mmdetection_td:${CONTAINER_CODE_PATH}/td
  - ${HOST_CODE_PATH}/pstr:${CONTAINER_CODE_PATH}/pstr
  - ${HOST_DATA_PATH}:${CONTAINER_DATA_PATH}:ro
  - ${HOST_MODELS_PATH}:${CONTAINER_MODELS_PATH}:ro
  # Grounding DINO
  - ${GROUNDING_DINO_MODEL_FOLDER}:${CONTAINER_HOME_PATH}/models_grounding_dino:ro
  - ${MINEX_MODEL_FOLDER}:${CONTAINER_HOME_PATH}/models_minex:ro

services:
  builder:
    <<: *executable
    build:
      target: builder
      args: 
        <<: *build-args
  
  base-devel:
    build:
      target: base_devel
      args: 
        <<: *build-args

  base-runtime:
    build:
      target: base_runtime
      args:
        <<: *build-args

  dev:
    build:
      target: dev
      args:
        <<:
          - *build-args
          - *dev-args
    environment:
        MLFLOW_TRACKING_URI: "/home/reusm/code/td/work_dirs/debug/train_mini/mlflow"
        TOKENIZERS_PARALLELISM: "false"
        TERM: 'screen-256color'

    <<: *executable
    entrypoint: /entrypoint.sh
    working_dir: ${CONTAINER_CODE_PATH}/td

    network_mode: host

    volumes:
      *dev-volumes
    shm_size: ${SHM_SIZE} 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  vscode:
    external: true
  torch_cache: 
    external: true

