name: mmdet
version: '3'

services:
  dev:
    build:
      target: dev
      context: .
      args:
        PYTORCH_VERSION: ${PYTORCH_VERSION}
        CUDA_VERSION: ${CUDA_VERSION}
        CUDNN_VERSION: ${CUDNN_VERSION}
        MMENGINE_VERSION_MAJOR: ${MMENGINE_VERSION_MAJOR}
        MMENGINE_VERSION_MINOR: ${MMENGINE_VERSION_MINOR}
        MMENGINE_VERSION_PATCH: ${MMENGINE_VERSION_PATCH}
        MMCV_VERSION_MAJOR: ${MMCV_VERSION_MAJOR}
        MMCV_VERSION_MINOR: ${MMCV_VERSION_MINOR}
        MMCV_VERSION_PATCH: ${MMCV_VERSION_PATCH}
        MIM_VERSION_MAJOR: ${MIM_VERSION_MAJOR}
        MIM_VERSION_MINOR: ${MIM_VERSION_MINOR}
        MIM_VERSION_PATCH: ${MIM_VERSION_PATCH}
        MMDET_VERSION: ${MMDET_VERSION}
        USERNAME: ${USERNAME}
        UID: ${UID}
        GID: ${GID}
        CONTAINER_HOME_PATH: ${CONTAINER_HOME_PATH}
        CONTAINER_CODE_PATH: ${CONTAINER_CODE_PATH}
        CONTAINER_TORCH_CACHE_PATH: ${CONTAINER_TORCH_CACHE_PATH}
        CONTAINER_VSCODE_PATH: ${CONTAINER_VSCODE_PATH}
    environment:
        TERM: 'screen-256color'

    tty: true
    init: true
    entrypoint: /entrypoint.sh

    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - torch_cache:${CONTAINER_TORCH_CACHE_PATH}
      - vscode:${CONTAINER_VSCODE_PATH}
      - ${HOST_CODE_PATH}/mmdet:${CONTAINER_CODE_PATH}/mmdet
      - ${HOST_DATASET_PATH}:${CONTAINER_DATASET_PATH}:ro
      - ${HOST_DATA_PATH}/CUHK-SYSU:${CONTAINER_DATA_PATH}/sysu:ro
      - ${HOST_DATA_PATH}/CUHK-PEDES:${CONTAINER_DATA_PATH}/pedes:ro
      - ${HOST_DATA_PATH}/COCODIR:${CONTAINER_DATA_PATH}/coco:ro
      - ${HOST_MODELS_PATH}:${CONTAINER_MODELS_PATH}:ro
    shm_size: ${SHM_SIZE} 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

  build:
    build:
      target: built-mmdet
      context: .
      args:
        PYTORCH_VERSION: ${PYTORCH_VERSION}
        CUDA_VERSION: ${CUDA_VERSION}
        CUDNN_VERSION: ${CUDNN_VERSION}
        MMDET_VERSION: ${MMDET_VERSION}

    tty: true
    init: true

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]


volumes:
  vscode:
    external: true
  torch_cache: 
    external: true
  workspace: 

