version: '3'
name: "pstr"

services:
  build:
    build:
      context: .
      target: build
      args:
        PYTORCH_VERSION: ${PYTORCH_VERSION}
        CUDA_VERSION: ${CUDA_VERSION}
        CUDNN_VERSION: ${CUDNN_VERSION}
    environment:
        TERM: 'screen-256color'

    tty: true
    init: true

  dev:
    build:
      context: .
      target: dev

      args:
        PYTORCH_VERSION: ${PYTORCH_VERSION}
        CUDA_VERSION: ${CUDA_VERSION}
        CUDNN_VERSION: ${CUDNN_VERSION}
        USERNAME: ${USERNAME}
        UID: ${UID}
        GID: ${GID}
        CONTAINER_HOME_PATH: ${CONTAINER_HOME_PATH}
        CONTAINER_TORCH_CACHE_PATH: ${CONTAINER_TORCH_CACHE_PATH}
        CONTAINER_VSCODE_PATH: ${CONTAINER_VSCODE_PATH}

    environment:
        TERM: 'screen-256color'
        CONTAINER_PS1: "PSTR [\\w] >> "

    volumes:
      - /home/reusm/code/Datasets/CUHK-SYSU:/workspace/data/cuhk:ro
      - /home/reusm/docker_space/pstr/entrypoint.sh:/home/reusm/entrypoint.sh
      - /home/reusm/code/models/pstr_resnet_cuhk/origin_trained_myself.pth:/workspace/model/pstr.pth:ro
      - vscode:${CONTAINER_VSCODE_PATH}
      - torch_cache:${CONTAINER_TORCH_CACHE_PATH}
    shm_size: "16G"
    network_mode: host
    entrypoint: /home/reusm/entrypoint.sh

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

    tty: true
    init: true



volumes:
  vscode:
  torch_cache:

