version: '3'

services:
  dev:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        USERNAME: ${USERNAME}

    env_file:
      - ./.env
    working_dir: ${CODE_PATH}
    entrypoint: /workspace/entrypoint.sh
    tty: true
    init: true

    user: "${UID}:${GID}"

    volumes:
      # Docker volumes
      - vscode:${CONTAINER_VSCODE_PATH}
      # Bind volumes
      - ${HOST_CODE_PATH}/cuhk-sysu-pedes/:${CONTAINER_CODE_PATH}/cuhk-sysu-pedes
      - ${HOST_DATA_PATH}/CUHK-SYSU/:${CONTAINER_DATA_PATH}/CUHK-SYSU:ro
      - ${HOST_DATA_PATH}/CUHK-PEDES/:${CONTAINER_DATA_PATH}/CUHK-PEDES:ro
volumes:
  vscode:
    external: true

